- name: Installing mysql libraries
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: pip3.9
  loop:
  - PyMySQL
  - cryptography

- name: Installing Mysql Database
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Enabeling and Starting server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Connecting to mysql-server
  community.mysql.mysql_info:
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    login_host: "{{ mysql.jobsearchindia.online }}"
  register: mysql_info
  ignore_errors: true

# - name: Printing the mysql_info details
#   ansible.builtin.debug:
#     msg: " {{ mysql_info }}"

- name: setting up the root password 
  ansible.builtin.command: " mysql_secure_installation --set-root-pass ExpenseApp@1 "
  when: mysql_info.failed == true
  